Robotic_Arm:  
  Robotic_Arm_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
    gains:
      arm_joint_1: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      arm_joint_2: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      arm_joint_3: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      arm_joint_4: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
