# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID

base:
  ID: 1
  Return_Delay_Time: 2
  Operating_Mode: 3
joint2:
  ID: 2
  Return_Delay_Time: 4
  Operating_Mode: 3

